### PR TITLE
Filter out keybase proofs

### PR DESCRIPTION
**Pull request by KonradIT**
This PR adds a filter so that keybase proofs are not included in the tweets to delete. It does this by detecting a substring.

### CODE REVIEW

**Comment by dysinger** [comment]
Feature #27 mentions this

**Comment by dysinger** [comment]
This P/R is almost 6 months old. I'd really like to have my KeyBase proof tweet back and have it stay without having to meet the minimum like/retweet requirements. @micahflee

**Comment by dysinger** [comment]
If the specificity of KeyBase in this P/R isn't desired then let's discuss something more generic (like maybe a list of specific tweets in the configuration that explicitly should never be deleted)

**Comment by micahflee** [comment]
Sorry I never responded to this! You can already do this. After fetching tweets for the first time, you can run `semiphemeral configure`, load http://127.0.0.1:8080/ and go to the tweets page, and mark whatever tweets you want (including your keybase tweet) to exclude from deletion.

**Pull request closed without merging**
